name: Unit Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
          check-latest: true
      - uses: actions/checkout@v3
      - name: Test
        run: |
          make test-unit
